### PR TITLE
Update codecov job in CI

### PR DESCRIPTION
**Pull request by FreezyLemon**
See discussion in #26. PRing from a branch on the main repo to see if the token actually works.

### CODE REVIEW

**Comment by FreezyLemon** [comment]
Seems okay. The `token` is mentioned in the job details and there's no warning about missing tokens in the logs.

**Review by Luni-4 — APPROVED** [review]
Thanks a lot! I forgot in the last PR a `>` which should be a `|` to be consistent with the rest of the script, but you can change that directly from `main` branch

**Comment by FreezyLemon** [comment]
I'll add it to this PR. It's kinda in scope because it's the same job. Give me a minute

**Comment by FreezyLemon** [comment]
Oh wait. I misread that. Oops, sorry for that

**Comment by Luni-4** [comment]
This one https://github.com/rust-av/v_frame/blob/main/.github/workflows/crate.yml#L55

To be consistent, we should use `|`

**Comment by FreezyLemon** [comment]
I'll go ahead and merge this because the commits after PR approval are just formatting changes

**Comment by Luni-4** [comment]
@FreezyLemon 

Here https://github.com/rust-av/v_frame/blob/main/.github/workflows/crate.yml#L64 we should replace `{{ name }}` with `v_frame`

**Comment by FreezyLemon** [comment]
Good catch, I created #28 for the fix.

**Pull request merged**
