### PR TITLE
Revert changes in downsampled which changed its behavior

### PR DESCRIPTION
**Pull request by shssoichiro**

### CODE REVIEW

**Review by lu-zero — APPROVED** [review]
Probably ok, can we add a test for when we reconsider changing it?

**Comment by shssoichiro** [comment]
What's interesting is we have two tests on `plane.downsampled`. I wonder if this only becomes a problem in certain cases, like based on the amount of padding in a frame? Although mindfreeze and I both were able to reproduce it in rav1e with just a random clip picked out of our inventory.

**Comment by shssoichiro** [comment]
I went ahead and merged it for now so we can get back to the previous, presumably desirable behavior, and we can do further investigation in the meantime.

**Comment by lu-zero** [comment]
If you can extract the configuration that causes the problem by logging via printf the values would be great ^^;

**Pull request merged**
