### PR TITLE
Version 0.3.8

### PR DESCRIPTION
**Pull request by shssoichiro**

### CODE REVIEW

**Comment by FreezyLemon** [comment]
Hold on a second, I just noticed a mistake in one of my PRs that was merged today..

**Comment by FreezyLemon** [comment]
Opened #34, just noticed that this got lost when rebasing. Sorry!

**Review by FreezyLemon — APPROVED** [review]

**Comment by FreezyLemon** [comment]
Not sure if we need to wait for confirmation from someone else?

**Comment by shssoichiro** [comment]
We should be good to go, thanks

**Pull request merged**
